apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
  annotations:
    postgres-operator.crunchydata.com/autoCreateUserSchema: "true"
spec:
  postgresVersion: 17
  users:
    - name: hippo
      databases:
        - zoo
  instances:
    - name: instance1
      containers:
      - name: perms-sidecar
        image: registry.access.redhat.com/ubi9/ubi:latest
        command: ["/bin/sh","-lc","sleep infinity"]
        volumeMounts:
        - name: pgdata
          mountPath: /pgdata
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh","-lc","chmod -R g+rwX /pgdata || true"]
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
