apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
  annotations:
    postgres-operator.crunchydata.com/autoCreateUserSchema: "true"
spec:
  postgresVersion: 17
  users:
    - name: hippo
      databases:
        - zoo
    - name: owui
      databases:
        - owui
    - name: obico
      databases:
        - obico
    - name: keycloak
      databases:
        - keycloak
  instances:
    - name: instance1
      replicas: 1
      initContainers:
        - name: fix-pgdata-perms
          image: registry.access.redhat.com/ubi9/ubi:latest
          command: ["chown", "-R", "26:26", "/pgdata"]
          volumeMounts:
            - name: postgres-data
              mountPath: /pgdata
          securityContext:
            runAsUser: 0
      dataVolumeClaimSpec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      repos:
        - name: repo1
          schedules:
            full: "0 1 * * 0"
            incremental: "0 1 * * 1-6"
          volume:
            volumeClaimSpec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
