apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
  annotations:
    postgres-operator.crunchydata.com/autoCreateUserSchema: "true"
spec:
  supplementalGroups: 
    - 65534
  postgresVersion: 17
  users:
    - name: hippo
      databases:
        - zoo
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
      podSpec:
        initContainers:
        - name: fix-permissions
          image: registry.access.redhat.com/ubi9/ubi:latest
          command:
            - /bin/sh
            - -c
            - |
              echo "Fixing permissions on /pgdata..."
              chown -R 26:26 /pgdata || true
              chmod -R ug+rwX /pgdata || true
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            privileged: false
          volumeMounts:
          - name: pgdata
            mountPath: /pgdata
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
